# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetflixRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetflixRxSwift
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxAlamofire'
pod 'RxDataSources'
end
